[project]
name = "ha-kvarta-c"
version = "0"
requires-python = ">=3.14.2"

[dependency-groups]
dev = [
    "beautifulsoup4",
    "black",
    "pytest-homeassistant-custom-component==0.13.368",
]

[tool.uv]
package = false

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
pythonpath = ["."]
