update_value:
  name: Update counter value
  description: Send new counter readings.
  target:
    entity:
      integration: kvartac
      domain: sensor
      device_class:
        - gas
        - volume
        - energy
  fields:
    value:
      name: Value
      description: The new counter readings to send. Must be greater than the previous one.
      example: "48"
      required: true
      selector:
        number:
          min: 1
          max: 999999
          mode: box
