update_value:
  description: Update counter value
  # target:
  #   entity:
  #     integration: "kvartac"
  #     domain: "sensor"
  fields:
    entity_id:
      description: Name of entity to update counter.
      # example: "light.living_room_lights"
      name: Entity
      required: true
      selector:
        entity:
          integration: kvartac
          domain: sensor
          device_class:
            - gas
            - volume
            - energy
    value:
      description: The new counter value to set
      name: Value
      required: true
      selector:
        number:
          min: 1
          max: 999999
