name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release-zip:
    name: Release ZIP
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v7"
      - name: ZIP Component folder
        run: |
          cd ${{ github.workspace }}/custom_components/kvartac
          zip -r kvartac.zip ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/kvartac/kvartac.zip
          asset_name: kvartac.zip
          tag: ${{ github.ref }}
          overwrite: true
